// Generates the PWA icons (192 & 512) as on-brand violet gradient PNGs, with no
// image library — a minimal PNG encoder — and writes them base64-encoded into
// src/web/icons.ts so the server can serve them without extra files.
const zlib = require('zlib');
const fs = require('fs');
const path = require('path');

const CRC_TABLE = (() => {
  const t = [];
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();
function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}
function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length, 0);
  const typeBuf = Buffer.from(type, 'ascii');
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([typeBuf, data])), 0);
  return Buffer.concat([len, typeBuf, data, crc]);
}
function lerp(a, b, t) { return Math.round(a + (b - a) * t); }

function makePng(size) {
  const c0 = [167, 139, 250]; // #A78BFA
  const c1 = [109, 40, 217]; // #6D28D9
  const raw = Buffer.alloc((1 + size * 4) * size);
  let p = 0;
  for (let y = 0; y < size; y++) {
    raw[p++] = 0; // filter: none
    const t = y / (size - 1);
    const r = lerp(c0[0], c1[0], t), g = lerp(c0[1], c1[1], t), b = lerp(c0[2], c1[2], t);
    for (let x = 0; x < size; x++) { raw[p++] = r; raw[p++] = g; raw[p++] = b; raw[p++] = 255; }
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // color type RGBA
  const sig = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  return Buffer.concat([sig, chunk('IHDR', ihdr), chunk('IDAT', zlib.deflateSync(raw)), chunk('IEND', Buffer.alloc(0))]);
}

const out = path.join(__dirname, '..', 'src', 'web');
fs.mkdirSync(out, { recursive: true });
const icon192 = makePng(192).toString('base64');
const icon512 = makePng(512).toString('base64');
fs.writeFileSync(
  path.join(out, 'icons.ts'),
  `// Auto-generated by scripts/gen-icons.js — PWA icons (violet gradient).\n` +
    `export const ICON_192 = '${icon192}';\n` +
    `export const ICON_512 = '${icon512}';\n`
);
console.log('🎨 icons.ts généré (192 & 512)');
